[package]
name = "budget-jira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "bjl"
path = "src/lib.rs"

[[bin]]
name = "budget_jira"
path = "src/bin.rs"

[dependencies]
chrono = "0.4.38"
clap = "4.5.21"
strum = "0.26.3"
strum_macros = "0.26.4"
